### ISSUE TITLE
ipop stat is not reported if node is behind home ISP

### ISSUE THREAD

**Issue by kyuhojeong** [ipop-project/ipop-tincan#100]
If the node is behind home ISP, it is very likely not to report ipop-stat. It may be caused by the unsolicited DNS or firewall rule(port restriction). I think the latter is more likely. We're currently using port number 5000.

**Comment by goldsoft8888** [comment]
Is it related to my question?
I was trying to find a bridge that caused the failure of the network.

**Comment by saumitraaditya** [comment]
Can you provide an update on this issue.

**Comment by kyuhojeong** [comment]
​It should be fixed since 16.01. Using port number 5000 instead of http
port such as 80 and 8080 was the problem.

​

On Thu, Feb 4, 2016 at 2:01 AM, Saumitra Aditya <notifications@github.com>
wrote:

> Can you provide an update on this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipop-project/ipop-tincan/issues/100#issuecomment-179377799>
> .
>



-- 
Kyuho Jeong

**Comment by kyuhojeong** [comment]
fixed
