### ISSUE TITLE
peer_state notifications about offline nodes

### ISSUE THREAD

**Issue by ssabogal** [ipop-project/ipop-tincan#102]
In the Controller-TinCan API, the controller receives peer_state notifications of peers of all nodes, including now-offline nodes, since the controller was run.

In other words, If node A and B are online, then A receives peer_state notifications about B. However, when B goes offline, A continues to receive peer_state notifications about B.

I have two proposed solutions:
1. Disallow peer_state notifications about nodes that are no longer online (any offline node).
2. Add an attribute to distinguish a node as online or offline.

Note:
This is not the same as the "status" attribute which only indicates if a tincan link with a node is active. An 'offline' value of this attribute is insufficient for distinguishing a node as online or offline.

**Comment by goldsoft8888** [comment]
"_ip4" : "172.172.1.2",
   "_ip6" : "fd50:0dbc:41f2:4a3c:4cd0:e3e8:7239:f909",
   "_mac" : "00:ff:87:c0:b0:58",
   "_uid" : "4cd0e3e87239f909fdc1b33ce90aa026d592afc0",
   "type" : "local_state"
}

DEBUG:root:recv ('::1', 5800, 0, 0) {
   "fpr" : "02:67:E1:F7:99:CC:BD:9C:47:D8:24:F9:71:F0:9C:9F:52:F9:5D:9F",
   "ip4" : "172.172.172.2",
   "ip6" : "fd50:0dbc:41f2:4a3c:d059:b601:1c12:da83",
   "last_time" : 49,
   "status" : "offline",
   "type" : "peer_state",
   "uid" : "d059b6011c12da83258236249ff46b9be54ebd4e",
   "xmpp_time" : 77
}

DEBUG:root:recv ('::1', 5800, 0, 0) {
   "_fpr" : "B3:60:57:B0:B3:4B:CA:6D:DF:7E:0A:E4:4B:51:F0:B9:9B:44:80:3C",
   "_ip4" : "172.172.1.2",
   "_ip6" : "fd50:0dbc:41f2:4a3c:4cd0:e3e8:7239:f909",
   "_mac" : "00:ff:87:c0:b0:58",
   "_uid" : "4cd0e3e87239f909fdc1b33ce90aa026d592afc0",
   "type" : "local_state"
}

DEBUG:root:recv ('::1', 5800, 0, 0) {
   "fpr" : "02:67:E1:F7:99:CC:BD:9C:47:D8:24:F9:71:F0:9C:9F:52:F9:5D:9F",
   "ip4" : "172.172.172.2",
   "ip6" : "fd50:0dbc:41f2:4a3c:d059:b601:1c12:da83",
   "last_time" : 79,
   "status" : "offline",
   "type" : "peer_state",
   "uid" : "d059b6011c12da83258236249ff46b9be54ebd4e",
   "xmpp_time" : 107
}

**Comment by kyuhojeong** [comment]
requires more investigation.

**Comment by saumitraaditya** [comment]
see if peer's xmpp state can be queried from client.

**Comment by saumitraaditya** [comment]
can't be fixed.
