### ISSUE TITLE
Symmetric NAT Traversal using STUN

### ISSUE THREAD

**Issue by goldsoft8888** [ipop-project/ipop-tincan#104]
The latest version of WEBRTC support RFC5780?
STUN SERVER software already provides support.
Or whether you can increase the RFC5780 standard IPOP in?

Symmetric NAT Traversal using STUN, TURN without using costly

http://tools.ietf.org/html/rfc5780

Symmetric NAT Traversal using STUN
http://tools.ietf.org/id/draft-takeda-symmetric-nat-traversal-00.txt
http://www.goto.info.waseda.ac.jp/~wei/file/wei-apan-v10.pdf

**Comment by pstjuste** [comment]
I don't think WebRTC supports symmetric NAT traversal yet. Once it is implemented, IPOP will get it for free.

**Comment by goldsoft8888** [comment]
ipoplib.py file, see the following:


    "stun": ["stun.l.google.com:19302", "stun1.l.google.com:19302",
              "stun2.l.google.com:19302", "stun3.l.google.com:19302",
              "stun4.l.google.com:19302"],


I can set up in config.json in it? With the above.
When I set up for multiple STUN SERVER in config.json, which is not in force.

**Comment by saumitraaditya** [comment]
won't fix
