### ISSUE TITLE
Continue forwarding packets to controller until TinCan link is established

### ISSUE THREAD

**Issue by renatof** [ipop-project/ipop-tincan#118]
When creating an on-demand link in GroupVPN, there is a lag of several seconds in having the link established, and packets are dropped during this time window. 

The problem is that during this time TinCan doesn't have a P2P link established yet, and the controller cannot take actions (e.g. overlay routing) to forward and deliver packets, because TinCan doesn't forward it up.

It would improve performance significantly if TinCan is able to a) detect when a P2P link is properly established, and b) forward messages to the controller until the P2P link is properly established.

**Comment by renatof** [comment]
It seems this is where in the code we should be looking at:

https://github.com/ipop-project/ipop-tincan/blob/devel/src/tincanconnectionmanager.cc#L345

If channel==null, the packet is not forwarded to the tincan p2p link, nor is it sent to the controller. It seems we should be able to send it up to the controller here.

**Comment by saumitraaditya** [comment]
fixed in release 16.08.1
