### ISSUE TITLE
Connection Error Ejabberd XMPP Server

### ISSUE THREAD

**Issue by ajar16** [ipop-project/ipop-tincan#59]
I get an error as follows when connecting to a xmpp server I created 

Error(schanneladpater.cc 235): InitializeSecurityContext error: SEC_E_UNTRUSTED_ROOT

This looks like self signed certificate of a XMPP server is not accepted by client. Is there a way to accept self signed certificate and connect ? 

Normally clients like Psi have an option of "Trust this Certificate " or "Connect Anyway". Is this option available in IpopTincan.

**Comment by kcratie** [comment]
Closing old "won't fix" issue.
