### ISSUE TITLE
Rasberry Pi Hang Issue

### ISSUE THREAD

**Issue by ajar16** [ipop-project/ipop-tincan#60]
While trying to install Ipop-Tincan on Rasbian OS in Rasberry Pi model B ,  I encountered an error in log.err related to UDP connection error due to IPV6 .  On investigating further I found that IPV6 is not enabled by default in Rasbian. 
So I enabled it using "sudo modprobe ipv6" 

However after this on launching IPOP TINCAN I get hang or crash like symptoms . I am accessing the rasberry pi via tightvnc over wifi . On launching IPOPTINCAN my TightVNC session is terminated and the rasberry pi does not respond to pings over the network. I have to restart the rasberry pi unit to restore functioning . Any suggestions on what I may try to resolve this.

**Comment by kyuhojeong** [comment]
no active support for rasberry pi at the moment.
