### ISSUE TITLE
XMPP server certificate verification on Linux

### ISSUE THREAD

**Issue by pstjuste** [ipop-project/ipop-tincan#62]
XMPP server certificate needs to be verified to preclude MITM attacks, use existing OpenSSL facilities to look up proper CA. Also it should allow user to add additional CA for IPOP-Tincan.

https://github.com/ipop-project/ipop-tincan/blob/cac23d2a526142087ed32e2249fb131c4c29bc4c/src/tincan.cc#L100

**Comment by renatof** [comment]
The move to XMPP client on the controller and support for certificate authentication should now make this simpler.

**Comment by saumitraaditya** [comment]
fixed in release 16.08.1.
