### ISSUE TITLE
Under Windows, interface name 'ipop' should not be hardcoded

### ISSUE THREAD

**Issue by ivucica** [ipop-project/ipop-tincan#80]
I already have OpenVPN installed, and I'd like to use the same networking interface while OpenVPN is not running. Please make the interface name configurable through `config.json`.

Currently, `ipop-tincan.exe` crashes completely when the interface is called, for example, `TAP`.

`win32_netsh_setup.py` also contains hardcoded name `ipop`, which was easier to replace given that it's a Python file and not a compiled binary.

**Comment by saumitraaditya** [comment]
resolved in 16.01
