### ISSUE TITLE
InitializeSecurityContext error: SEC_I_INCOMPLETE_CREDENTIALS

### ISSUE THREAD

**Issue by ivucica** [ipop-project/ipop-tincan#81]
Connecting to both my personal server and to jabber.org, I'm getting the following in tincan's window:

    Error(schanneladapter.cc:235): InitializeSecurityContext error: SEC_I_INCOMPLETE_CREDENTIALS

This is obviously coming from `libjingle` and is Windows specific.

This is while using ipop-14.07.0-x86_win7 binary distribution under Windows 8.1.

**Comment by rosaldorosa** [comment]
I followed excactly what was written above:
1. installed crt certificate file in both Mozilla and in Internet explorer.
2. I'm see certificate in Trusted root certifictates
3. Each time I try to open the page in IE Ie says : certificate error ( next to address), but opens it smoothly 
but still get same error (below log):
tincan::XmppNetwork::Connect: tincan::XmppNetwork::Connect: XMPP CONNECTING
tincan::XmppNetwork::OnStateChange: tincan::XmppNetwork::OnStateChange: OPENING
Error(schanneladapter.cc:235): InitializeSecurityContext error: SEC_E_UNTRUSTED_
ROOT
Warning(schanneladapter.cc:418): SChannelAdapter::Error(ContinueSSL, SEC_E_UNTRU
STED_ROOT)
tincan::XmppNetwork::OnCloseEvent: tincan::XmppNetwork::OnCloseEvent: ONCLOSEEVE
NT -2146893019

**Comment by rosaldorosa** [comment]
COuld it be that CaCert Class 3 Root is not supported

**Comment by pstjuste** [comment]
I hope you are not installing the certificates through the browser. If you add them through the browser, then they are only trusted by the browser. You need to add them to the Windows root certificates http://blogs.adobe.com/livecycle/2012/04/rights-management-how-to-get-windows-7-to-trust-a-self-signed-server-certificate.html

**Comment by saumitraaditya** [comment]
won't fix
