### ISSUE TITLE
Problem of connect 2 computers (win7) behind 2 NATs

### ISSUE THREAD

**Issue by he-pe** [ipop-project/ipop-tincan#85]
https://github.com/ipop-project/documentation/wiki/Running-SocialVPN-on-Windows-7
This instruction are executed precisely

Jabber service: xmpp.ru (jabber.ru)

Computer 1
176.15.196.41; local 192.168.1.15
{
    "xmpp_username": "...@xmpp.ru",
    "xmpp_host": "xmpp.ru",
    "xmpp_password": "...",
    "ip4": "10.13.0.1",
    "ip4_mask": 24,
    "controller_logging": "DEBUG",
    "tincan_logging": 2
}

Computer 2
194.84.170.16; local 192.168.2.200
{
    "xmpp_username": "...@xmpp.ru",
    "xmpp_host": "xmpp.ru",
    "xmpp_password": "...",
    "ip4": "10.13.0.2",
    "ip4_mask": 24,
    "controller_logging": "DEBUG",
    "tincan_logging": 2
}

ipop-tin-can.exe:
tincan::XmppNetwork::Connect: tincan::XmppNetwork::Connect: XMPP CONNECTING
tincan::XmppNetwork::OnStateChange: tincan::XmppNetwork::OnStateChange: OPENING
tincan::XmppNetwork::OnStateChange: tincan::XmppNetwork::OnStateChange: OPEN
tincan::XmppNetwork::OnSignOn: tincan::XmppNetwork::OnSignOn: XMPP ONLINE ...@xmpp.ru/tincand41f334639018736946815a550279a5898cc4985
tincan::XmppNetwork::OnPresenceMessage: tincan::XmppNetwork::OnPresenceMessage:
uid ...@xmpp.ru/tincand35b91081c87f31e2e59dab7412a1046f660876c st
atus
tincan::XmppNetwork::OnPresenceMessage: tincan::XmppNetwork::OnPresenceMessage:
uid ...@xmpp.ru/tincan78d6e35727ef258303151e8b5ca898f163f1a0be st
atus
tincan::ControllerAccess::SendToPeer: tincan::ControllerAccess::SendToPeer: uid:
78d6e35727ef258303151e8b5ca898f163f1a0be data:00:00:00:00:00:00:00:00:00:00:00:0
0:00:00:00:00:00:00:00:00 type:con_req
...
There is log very long.

Jingle:Conn[ipop-tincan:yYOmUGGq:1:0:local:tcp:192.168.1.15:49765->TiTqOQfG:1:0:
local:tcp:192.168.2.200:49953|C--W|-]: Connection created
Jingle:Channel[ipop-tincan|1|__]: Created connection with origin=2, (5 total)
Jingle:Net[╨Р╨┤╨░╨┐╤В╨╡╤А:192.168.1.15/32]: Allocation Phase=SslTcp
All candidates gathered for ipop-tincan:1:0
Transport: ipop-tincan, component 1 allocation complete
Transport: ipop-tincan allocation complete
tincan::TinCanTask::SendToPeer: tincan::TinCanTask::SendToPeer: XMPP SEND uid 78
d6e35727ef258303151e8b5ca898f163f1a0be data 00:00:00:00:00:00:00:00:00:00:00:00:
00:00:00:00:00:00:00:00 5X7RkmAd:1:udp:176.15.196.41:55149:1845501695:lJ1+wAUUGC
kAB0bE:AQOBCmOU8y1mpDw/qvrXsvQs:stun:╨Я╨╛╨┤╨║╨╗╤О╤З╨╡╨╜╨╕╨╡:0:851719950 LXJRTbyX
:1:udp:192.168.1.15:55148:2113937151:l5zPao6RpIsX3g2p:MxVHJ0kdpbYOQM+OhaUWmd2+:l
ocal:╨Я╨╛╨┤╨║╨╗╤О╤З╨╡╨╜╨╕╨╡:0:3302248154 yYOmUGGq:1:tcp:192.168.1.15:49765:15099
57375:G39NqDbY9xCeesZc:6dy3Qp7Rzgjk74doDrSs4E06:local:╨Я╨╛╨┤╨║╨╗╤О╤З╨╡╨╜╨╕╨╡:0:2
321003050 type con_resp
tincan::ControllerAccess::SendToPeer: tincan::ControllerAccess::SendToPeer: uid:
78d6e35727ef258303151e8b5ca898f163f1a0be data:unknown type:con_stat
Jingle:Conn[ipop-tincan:5X7RkmAd:1:0:stun:udp:176.15.196.41:55149->Rlb33eF9:1:0:
stun:udp:194.84.170.16:54898|CRWS|-]: Received STUN ping response nOu4pJJQR2M/,
pings_since_last_response_=116995560 116995760 116995961 116996161 116996361 116
996562 116996762 116996962 116997162 116997363 116997563 116997763 116997964 116
998164 116998364 116998564 , rtt=10
Jingle:Channel[ipop-tincan|1|R_]: Previous best connection: Conn[ipop-tincan:LXJ
RTbyX:1:0:local:udp:192.168.1.15:55148->aZWpNiTw:1:0:local:udp:192.168.2.200:548
97|C--I|-]
Jingle:Channel[ipop-tincan|1|R_]: New best connection: Conn[ipop-tincan:5X7RkmAd
:1:0:stun:udp:176.15.196.41:55149->Rlb33eF9:1:0:stun:udp:194.84.170.16:54898|CRW
S|2252]
tincan::TinCanConnectionManager::OnRWChangeState: tincan::TinCanConnectionManage
r::OnRWChangeState: ONLINE 78d6e35727ef258303151e8b5ca898f163f1a0be 116998574
Jingle:Conn[ipop-tincan:yYOmUGGq:1:0:local:tcp:192.168.1.15:49765->TiTqOQfG:1:0:
local:tcp:192.168.2.200:49953|--xW|-]: Connection deleted
tincan::ControllerAccess::SendToPeer: tincan::ControllerAccess::SendToPeer: uid:
78d6e35727ef258303151e8b5ca898f163f1a0be data:online type:con_stat
Jingle:Channel[ipop-tincan|1|RW]: Removed connection (4 remaining)
Jingle:Conn[ipop-tincan:5X7RkmAd:1:0:stun:udp:176.15.196.41:55149->Rlb33eF9:1:0:
stun:udp:194.84.170.16:54898|CRWS|1271]: Timing-out STUN ping ULo2dhwEkwO0 after
 5007 ms
...
...

At end:
tincan::XmppNetwork::OnPresenceMessage: tincan::XmppNetwork::OnPresenceMessage:
uid ...@xmpp.ru/tincan78d6e35727ef258303151e8b5ca898f163f1a0be st
atus
tincan::XmppNetwork::OnPresenceMessage: tincan::XmppNetwork::OnPresenceMessage:
uid ...@xmpp.ru/tincan78d6e35727ef258303151e8b5ca898f163f1a0be st
atus
tincan::XmppNetwork::OnPresenceMessage: tincan::XmppNetwork::OnPresenceMessage:
uid ...@xmpp.ru/tincan78d6e35727ef258303151e8b5ca898f163f1a0be st
atus
...

And nothing more...

No PING to 10.13.0.2
No RDP to 10.13.0.2 (telnet 10.13.0.2 3389)
No Network browsing

On Computer 2:
No PING to 10.13.0.1
No RDP to 10.13.0.1 (telnet 10.13.0.1 3389)
No Network browsing

Firewalls off.
This test on version ipop-14.01.1-x86_32_win7
Version ipop-14.07.0-x86_win7 - same result.

Help to connect these 2 computers please.

**Comment by saumitraaditya** [comment]
resolved
