### ISSUE TITLE
Download SocialVPN for Windows link NOT work

### ISSUE THREAD

**Issue by resetled** [ipop-project/ipop-tincan#93]
https://github.com/ipop-project/documentation/wiki/Running-SocialVPN-on-Windows-7
On this page there are no working link to the executable file (http://goo.gl/tgdp6r). If you can - fill the exe-file to the google-drive or other file service.

Best regards.

**Comment by pstjuste** [comment]
I have added this link to the wiki page https://github.com/ipop-project/downloads/releases/download/v15.01.0/ipop-v15.01.0-x86_win7.zip but the google url shortener may will need to be updated

**Comment by resetled** [comment]
thank you very much!
