### ISSUE TITLE
Not sure if connected

### ISSUE THREAD

**Issue by rosaldorosa** [ipop-project/ipop-tincan#96]
on ipo-tincan.exe:
Error(stunport.cc:106): Binding request timed out from IP:
On cmd.exe:
DEBUG:root:recv ('::1', 5800, 0, 0) {
   "fpr" : "3B:F0:A9:E9:54:15:C5:45:58:AE:DE:A3:DF:05:AF:20:E6:18:0D:6E",
   "ip4" : "172.31.0.101",
   "ip6" : "fd50:0dbc:41f2:4a3c:2adc:5353:e87b:ebc9",
   "last_time" : 819,
   "security" : "dtls",
   "status" : "online",
   "type" : "peer_state",
   "uid" : "2adc5353e87bebc91cf75433f9fa8c16fb68f7b5",
   "xmpp_time" : 29
Am I online?
Because I can ping computers on the network 172.31.0.100/24 which are not socialvpn clients (at least 8)

**Comment by rosaldorosa** [comment]
On other end I have:
Jingle:Conn[ipop-tincan:lpInr+kg:1:0:stun:udp:46.112.169.37:60097->VFetEjpD:1:0.
78:stun:udp:94.135.161.226:54213|CRWS|7239851959911988734|110]: Timing-out STUN
ping j3u1PZlhYiU7 after 5008 ms
tincan::TinCanConnectionManager::OnNetworksChanged: tincan::TinCanConnectionMana
ger::OnNetworksChanged: IPOP TAP Device to be ignored 0:TAP-Windows Adapter V9
Robert

**Comment by renatof** [comment]
Robert,
As far as I can tell, you are online as in "logged into XMPP", but not
necessarily online as in "a socialvpn link exists". it's hard to say what
is going on; it might be an issue with NAT/firewall traversal (are you only
using STUN, or also TURN).
it'd help to have the configuration you used in your test.
--rf
